spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Spring_lab6
    username: root
    password: Tu100den10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
